#pragma once

#define KRYS_MOUSE_BUTTON_1         0
#define KRYS_MOUSE_BUTTON_2         1
#define KRYS_MOUSE_BUTTON_3         2
#define KRYS_MOUSE_BUTTON_4         3
#define KRYS_MOUSE_BUTTON_5         4
#define KRYS_MOUSE_BUTTON_6         5
#define KRYS_MOUSE_BUTTON_7         6
#define KRYS_MOUSE_BUTTON_8         7
#define KRYS_MOUSE_BUTTON_LAST      KRYS_MOUSE_BUTTON_8
#define KRYS_MOUSE_BUTTON_LEFT      KRYS_MOUSE_BUTTON_1
#define KRYS_MOUSE_BUTTON_RIGHT     KRYS_MOUSE_BUTTON_2
#define KRYS_MOUSE_BUTTON_MIDDLE    KRYS_MOUSE_BUTTON_3